source /usr/local/etc/profile.d/bash_completion.sh


#.bash_profile
export LC_ALL=en_US.UTF-8

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# SUPPRESS THAT STUPID OSX THING
export BASH_SILENCE_DEPRECATION_WARNING=1

eval "$(gh completion -s bash)"

