set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

# Terminal & Colors (24-bit True Color support for Neovim)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Fast Escape time & Focus events
set -sg escape-time 10
set -g focus-events on

# History & Indexing
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Mouse & Vi mode
set -g mouse on
set -g mode-keys vi
set -g status-keys vi

# Copy mode bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Keybindings
bind S new-session
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded!"
bind-key ∂ popup

# Status bar
set -g status-style 'fg=white, bg=black'
set -g status-right "[#h]"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-urlview'

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-save-interval '10'

# Auto-install TPM if missing
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

run '~/.local/share/tmux/plugins/tpm/tpm'
